name: Build and Deploy Zola

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build Zola
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          # Le token est fourni automatiquement par GitHub
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
